openapi: 3.0.2
info:
  title: POS
  version: 1.0.0
  description: A simple REST API to manage sales
servers:
  - url: http://localhost:5000
    description: ""
paths:
  /customers:
    summary: Perform operations related to the Clients module
    description: Perform operations related to the Clients module
    get:
      tags:
        - Customers
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getAllcustomersResponse"
          description: Customers list
      operationId: getAllCustomers
      summary: Retrieve customer list
      description: Retrieve customer list
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createCustomerRequest"
        required: true
      tags:
        - Customers
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createCustomerResponse"
          description: Response after creating a new client
      operationId: createCustomer
      summary: Create a new customer
      description: Create a new customer
components:
  schemas:
    createCustomerRequest:
      description: Payload for creating a new customer
      required:
        - name
        - identification
      type: object
      properties:
        name:
          description: Customer name
          type: string
          example: Jhon Doe
        identification:
          description: Customer identification
          type: string
          example: "9876543210"
      example:
        name: Jhon Doe
        identification: "9876543210"
    getAllcustomersResponse:
      title: Root Type for customerResponse
      description: Response obtained when creating a new customer
      required:
        - status
        - title
        - code
        - data
      type: object
      properties:
        status:
          description: Response status
          enum:
            - success
            - failure
          type: string
          readOnly: true
          example: success
        title:
          description: HTTP response title
          type: string
          readOnly: true
          example: Ok
        code:
          description: HTTP response code
          maximum: 3
          minimum: 3
          type: integer
          readOnly: true
          example: "200"
        data:
          description: Customer data
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/customer"
          readOnly: true
          example: |-
            [
                {
                    "id": "ba4d4784-06dc-478d-a4ea-7aac65a30fee",
                    "name": "Jhon Doe",
                    "identification": "9876543210",
                    "updatedAt": "2024-11-10T00:00:00.000Z",
                    "createdAt": "2024-11-10T00:00:00.000Z"
                }
            ]
      additionalProperties: false
      example:
        status: success
        title: Ok
        code: 200
        data:
          - id: ba4d4784-06dc-478d-a4ea-7aac65a30fee
            name: Jhon Doe
            identification: "9876543210"
            updatedAt: "0000-00-00T00:00:00.000Z"
            createdAt: "0000-00-00T00:00:00.000Z"
    customer:
      title: Root Type for customer
      description: Customer object
      required:
        - id
        - name
        - identification
        - createdAt
        - updatedAt
      type: object
      properties:
        id:
          $ref: "#/components/schemas/uuid"
          description: UUID
          maxLength: 36
          minLength: 36
          pattern: /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$/
          readOnly: true
          example: ba4d4784-06dc-478d-a4ea-7aac65a30fee
        name:
          description: Customer name
          type: string
          readOnly: true
          example: Jhon Doe
        identification:
          description: Customer identification
          maxLength: 10
          minLength: 10
          type: string
          readOnly: true
          example: "9876543210"
        updatedAt:
          $ref: "#/components/schemas/date"
          description: Record update time
          example: "0000-00-00T00:00:00.000Z"
        createdAt:
          $ref: "#/components/schemas/date"
          description: Record creation time
          example: "0000-00-00T00:00:00.000Z"
      example:
        id: ba4d4784-06dc-478d-a4ea-7aac65a30fee
        name: Jhon Doe
        identification: "9876543210"
        updatedAt: "0000-00-00T00:00:00.000Z"
        createdAt: "0000-00-00T00:00:00.000Z"
    uuid:
      format: binary
      description: Universal unique identifier
      type: string
      example: ba4d4784-06dc-478d-a4ea-7aac65a30fee
    createCustomerResponse:
      title: Root Type for customerResponse
      description: Response obtained when creating a new customer
      required:
        - status
        - title
        - code
        - data
      type: object
      properties:
        status:
          description: Response status
          enum:
            - success
            - failure
          type: string
          readOnly: true
          example: success
        title:
          description: HTTP response title
          type: string
          readOnly: true
          example: Created
        code:
          description: HTTP response code
          maximum: 3
          minimum: 3
          type: integer
          readOnly: true
          example: 201
        data:
          $ref: "#/components/schemas/customer"
          description: Customer data
          minItems: 1
          uniqueItems: true
          readOnly: true
          example: |-
            {
                "id": "ba4d4784-06dc-478d-a4ea-7aac65a30fee",
                "name": "Jhon Doe",
                "identification": "9876543210",
                "updatedAt": "2024-11-10T00:00:00.000Z",
                "createdAt": "2024-11-10T00:00:00.000Z"
            }
      additionalProperties: false
      example:
        status: success
        title: Created
        code: 201
        data:
          id: ba4d4784-06dc-478d-a4ea-7aac65a30fee
          name: Jhon Doe
          identification: "9876543210"
          updatedAt: "0000-00-00T00:00:00.000Z"
          createdAt: "0000-00-00T00:00:00.000Z"
    date:
      format: date
      description: Date
      type: string
      example: "0000-00-00T00:00:00.000Z"
tags:
  - name: Customers
    description: Customers module
  - name: Products
    description: ""
  - name: Orders
    description: Orders module
